version: '3'
services:
  openhab:
    image: openhab/openhab
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /home/mike/openhab-volumes/conf:/openhab/conf
      - /home/mike/openhab-volumes/userdata:/openhab/userdata
      - /home/mike/openhab-volumes/addons:/openhab/addons
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    tty: true
    stdin_open: true
    restart: always
