version: '2'
services:
  openhab:
    image: openhab/openhab:2.0.0-amd64
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /home/mike/openhab-volumes/conf:/openhab/conf
      - /home/mike/openhab-volumes/userdata:/openhab/userdata
      - /home/mike/openhab-volumes/addons:/openhab/addons
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    tty: true
    stdin_open: true
    restart: always
    environment:
      OPENHAB_HTTP_PORT: "3000"
      OPENHAB_HTTPS_PORT: "8443"
